version: '3'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '8080:8080'

    backend:
        build: .
        ports:
            - '5000:5000'
        environment:
            - FLASK_ENV=production
